// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetListIDHandlerFunc turns a function with the right signature into a get list ID handler
type GetListIDHandlerFunc func(GetListIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetListIDHandlerFunc) Handle(params GetListIDParams) middleware.Responder {
	return fn(params)
}

// GetListIDHandler interface for that can handle valid get list ID params
type GetListIDHandler interface {
	Handle(GetListIDParams) middleware.Responder
}

// NewGetListID creates a new http.Handler for the get list ID operation
func NewGetListID(ctx *middleware.Context, handler GetListIDHandler) *GetListID {
	return &GetListID{Context: ctx, Handler: handler}
}

/*GetListID swagger:route GET /list/{id} getListId

Get list by id

*/
type GetListID struct {
	Context *middleware.Context
	Handler GetListIDHandler
}

func (o *GetListID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetListIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
