// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/erkartik91/service-babynames/models"
)

// PostListOKCode is the HTTP code returned for type PostListOK
const PostListOKCode int = 200

/*PostListOK OK

swagger:response postListOK
*/
type PostListOK struct {

	/*
	  In: Body
	*/
	Payload *models.List `json:"body,omitempty"`
}

// NewPostListOK creates PostListOK with default headers values
func NewPostListOK() *PostListOK {

	return &PostListOK{}
}

// WithPayload adds the payload to the post list o k response
func (o *PostListOK) WithPayload(payload *models.List) *PostListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post list o k response
func (o *PostListOK) SetPayload(payload *models.List) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostListDefault Error

swagger:response postListDefault
*/
type PostListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostListDefault creates PostListDefault with default headers values
func NewPostListDefault(code int) *PostListDefault {
	if code <= 0 {
		code = 500
	}

	return &PostListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post list default response
func (o *PostListDefault) WithStatusCode(code int) *PostListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post list default response
func (o *PostListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post list default response
func (o *PostListDefault) WithPayload(payload *models.Error) *PostListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post list default response
func (o *PostListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
