// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostListHandlerFunc turns a function with the right signature into a post list handler
type PostListHandlerFunc func(PostListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostListHandlerFunc) Handle(params PostListParams) middleware.Responder {
	return fn(params)
}

// PostListHandler interface for that can handle valid post list params
type PostListHandler interface {
	Handle(PostListParams) middleware.Responder
}

// NewPostList creates a new http.Handler for the post list operation
func NewPostList(ctx *middleware.Context, handler PostListHandler) *PostList {
	return &PostList{Context: ctx, Handler: handler}
}

/*PostList swagger:route POST /list postList

Create new list

*/
type PostList struct {
	Context *middleware.Context
	Handler PostListHandler
}

func (o *PostList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
