// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/erkartik91/service-babynames/models"
)

// PutListIDAddBabyNameOKCode is the HTTP code returned for type PutListIDAddBabyNameOK
const PutListIDAddBabyNameOKCode int = 200

/*PutListIDAddBabyNameOK OK

swagger:response putListIdAddBabyNameOK
*/
type PutListIDAddBabyNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.List `json:"body,omitempty"`
}

// NewPutListIDAddBabyNameOK creates PutListIDAddBabyNameOK with default headers values
func NewPutListIDAddBabyNameOK() *PutListIDAddBabyNameOK {

	return &PutListIDAddBabyNameOK{}
}

// WithPayload adds the payload to the put list Id add baby name o k response
func (o *PutListIDAddBabyNameOK) WithPayload(payload *models.List) *PutListIDAddBabyNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put list Id add baby name o k response
func (o *PutListIDAddBabyNameOK) SetPayload(payload *models.List) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutListIDAddBabyNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutListIDAddBabyNameDefault Error

swagger:response putListIdAddBabyNameDefault
*/
type PutListIDAddBabyNameDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutListIDAddBabyNameDefault creates PutListIDAddBabyNameDefault with default headers values
func NewPutListIDAddBabyNameDefault(code int) *PutListIDAddBabyNameDefault {
	if code <= 0 {
		code = 500
	}

	return &PutListIDAddBabyNameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put list ID add baby name default response
func (o *PutListIDAddBabyNameDefault) WithStatusCode(code int) *PutListIDAddBabyNameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put list ID add baby name default response
func (o *PutListIDAddBabyNameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put list ID add baby name default response
func (o *PutListIDAddBabyNameDefault) WithPayload(payload *models.Error) *PutListIDAddBabyNameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put list ID add baby name default response
func (o *PutListIDAddBabyNameDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutListIDAddBabyNameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
