// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutListIDAddBabyNameHandlerFunc turns a function with the right signature into a put list ID add baby name handler
type PutListIDAddBabyNameHandlerFunc func(PutListIDAddBabyNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutListIDAddBabyNameHandlerFunc) Handle(params PutListIDAddBabyNameParams) middleware.Responder {
	return fn(params)
}

// PutListIDAddBabyNameHandler interface for that can handle valid put list ID add baby name params
type PutListIDAddBabyNameHandler interface {
	Handle(PutListIDAddBabyNameParams) middleware.Responder
}

// NewPutListIDAddBabyName creates a new http.Handler for the put list ID add baby name operation
func NewPutListIDAddBabyName(ctx *middleware.Context, handler PutListIDAddBabyNameHandler) *PutListIDAddBabyName {
	return &PutListIDAddBabyName{Context: ctx, Handler: handler}
}

/*PutListIDAddBabyName swagger:route PUT /list/{id}/add-baby-name putListIdAddBabyName

Add given name to list

*/
type PutListIDAddBabyName struct {
	Context *middleware.Context
	Handler PutListIDAddBabyNameHandler
}

func (o *PutListIDAddBabyName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutListIDAddBabyNameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
